name: Build and deploy Python app to Azure Web App - rikkei-ocr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and activate virtual environment (temporary use only)
        run: |
          python -m venv /tmp/venv
          source /tmp/venv/bin/activate

      - name: Install dependencies
        run: |
          /tmp/venv/bin/pip install -r requirements.txt

      - name: Zip project files for deployment (exclude unnecessary folders)
        run: |
          zip -r release.zip . -x "venv/*" ".git/*" ".github/*" "__pycache__/*"

      - name: Upload artifact for deploy step
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip release.zip
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_79BCB34310064CD7BAC668AF47253AA6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F3EFC4E5358C4489B4DD12E42B9EE562 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_25A0CE02A04F4FCEAF355CE4E82B838F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'rikkei-ocr'
          slot-name: 'production'
          package: release.zip
